import type { Room } from "@/lib/room-directory";

export const initialCampusRooms: Room[] = [
  { id: "room-01", number: "01", floor: "Subsolo", segment: "Fundamental 1", morningClasses: ["2° MA"], afternoonClasses: ["2° TA"] },
  { id: "room-02", number: "02", floor: "Subsolo", segment: "Contraturno", morningClasses: ["Contraturno"], afternoonClasses: ["Contraturno"] },
  { id: "room-03", number: "03", floor: "Subsolo", segment: "Contraturno", morningClasses: ["Contraturno"], afternoonClasses: ["Contraturno"] },
  { id: "room-04", number: "04", floor: "Subsolo", segment: "Contraturno", morningClasses: ["Contraturno"], afternoonClasses: ["Contraturno"] },
  { id: "room-05", number: "05", floor: "Subsolo", segment: "Educação Infantil", morningClasses: ["MAT. MA"], afternoonClasses: ["MAT. TA"] },
  { id: "room-06", number: "06", floor: "Subsolo", segment: "Educação Infantil", morningClasses: ["PRÉ I MA"], afternoonClasses: ["PRÉ I TA"] },
  { id: "room-07", number: "07", floor: "Subsolo", segment: "Educação Infantil", morningClasses: ["PRÉ II MB"], afternoonClasses: ["PRÉ II TB"] },
  { id: "room-08", number: "08", floor: "1º piso", segment: "Fundamental 1", morningClasses: ["1° MC"], afternoonClasses: ["1° TC"] },
  { id: "room-09", number: "09", floor: "1º piso", segment: "Fundamental 1", morningClasses: ["2° MC"], afternoonClasses: ["2° TD"] },
  { id: "room-10", number: "10", floor: "1º piso", segment: "Fundamental 1", morningClasses: ["2° MB"], afternoonClasses: ["2° TB"] },
  { id: "room-11", number: "11", floor: "1º piso", segment: "Fundamental 1", morningClasses: [], afternoonClasses: ["2° TC"] },
  { id: "room-12", number: "12", floor: "1º piso", segment: "Fundamental 1", morningClasses: ["1° MB"], afternoonClasses: ["1° TB"] },
  { id: "room-13", number: "13", floor: "1º piso", segment: "Fundamental 1", morningClasses: ["1° MA"], afternoonClasses: ["1° TA"] },
  { id: "room-14", number: "14", floor: "1º piso", segment: "Educação Infantil", morningClasses: ["PRÉ II MA"], afternoonClasses: ["PRÉ II TA"] },
  { id: "room-15", number: "15", floor: "1º piso", segment: "Fundamental 1", morningClasses: ["5° MC"], afternoonClasses: ["5° TC"] },
  { id: "room-16", number: "16", floor: "1º piso", segment: "Fundamental 1", morningClasses: ["5° MB"], afternoonClasses: ["5° TB"] },
  { id: "room-17", number: "17", floor: "1º piso", segment: "Fundamental 1", morningClasses: ["5° MA"], afternoonClasses: ["5° TA"] },
  { id: "room-18", number: "18", floor: "2º piso", segment: "Fundamental 1", morningClasses: ["3° MD"], afternoonClasses: ["3° TD"] },
  { id: "room-19", number: "19", floor: "2º piso", segment: "Fundamental 1", morningClasses: ["3° MC"], afternoonClasses: ["3° TC"] },
  { id: "room-20", number: "20", floor: "2º piso", segment: "Fundamental 1", morningClasses: ["3° MB"], afternoonClasses: ["3° TB"] },
  { id: "room-21", number: "21", floor: "2º piso", segment: "Fundamental 1", morningClasses: ["3° MA"], afternoonClasses: ["3° TA"] },
  { id: "room-22", number: "22", floor: "2º piso", segment: "Fundamental 2", morningClasses: ["7° MA"], afternoonClasses: [] },
  { id: "room-23", number: "23", floor: "2º piso", segment: "Ensino Médio", morningClasses: ["1° EM MC"], afternoonClasses: [] },
  { id: "room-24", number: "24", floor: "2º piso", segment: "Fundamental 2", morningClasses: ["7° MC"], afternoonClasses: ["5° TD"] },
  { id: "room-25", number: "25", floor: "2º piso", segment: "Fundamental 2", morningClasses: ["6° MD"], afternoonClasses: ["6° TD"] },
  { id: "room-26", number: "26", floor: "2º piso", segment: "Fundamental 2", morningClasses: ["6° MC"], afternoonClasses: ["6° TC"] },
  { id: "room-27", number: "27", floor: "2º piso", segment: "Fundamental 2", morningClasses: ["6° MB"], afternoonClasses: ["6° TA"] },
  { id: "room-28", number: "28", floor: "2º piso", segment: "Fundamental 2", morningClasses: ["6° MA"], afternoonClasses: ["6° TA"] },
  { id: "room-29", number: "29", floor: "2º piso", segment: "Fundamental 2", morningClasses: ["8° MC"], afternoonClasses: ["1° EM TA"] },
  { id: "room-30", number: "30", floor: "2º piso", segment: "Fundamental 2", morningClasses: ["8° MB"], afternoonClasses: ["3° EM TA"] },
  { id: "room-31", number: "31", floor: "2º piso", segment: "Fundamental 2", morningClasses: ["9° MA"], afternoonClasses: ["1° EM TC"] },
  { id: "room-32", number: "32", floor: "2º piso", segment: "Ensino Médio", morningClasses: ["2° EM MC"], afternoonClasses: ["9° TB"] },
  { id: "room-33", number: "33", floor: "3º piso", segment: "Fundamental 1", morningClasses: ["4° MC"], afternoonClasses: ["4° TC"] },
  { id: "room-34", number: "34", floor: "3º piso", segment: "Fundamental 1", morningClasses: ["4° MB"], afternoonClasses: ["4° TB"] },
  { id: "room-35", number: "35", floor: "3º piso", segment: "Fundamental 1", morningClasses: ["4° MA"], afternoonClasses: ["4° TA"] },
  { id: "room-36", number: "36", floor: "3º piso", segment: "Ensino Médio", morningClasses: ["INT-2° CN"], afternoonClasses: ["INT-1° CN"] },
  { id: "room-37", number: "37", floor: "3º piso", segment: "Ensino Médio", morningClasses: ["2° EM MA"], afternoonClasses: ["7° TB"] },
  { id: "room-38", number: "38", floor: "3º piso", segment: "Fundamental 2", morningClasses: ["9° MC"], afternoonClasses: ["1° EM TB"] },
  { id: "room-39", number: "39", floor: "3º piso", segment: "Fundamental 2", morningClasses: ["8° MA"], afternoonClasses: ["2° EM TA"] },
  { id: "room-40", number: "40", floor: "3º piso", segment: "Ensino Médio", morningClasses: ["3° EM MB"], afternoonClasses: ["8° TB"] },
  { id: "room-41", number: "41", floor: "3º piso", segment: "Fundamental 2", morningClasses: ["9° MB"], afternoonClasses: ["3° EM TB"] },
  { id: "room-42", number: "42", floor: "3º piso", segment: "Fundamental 2", morningClasses: ["7° MB"], afternoonClasses: ["2° EM TB"] },
  { id: "room-43", number: "43", floor: "3º piso", segment: "Ensino Médio", morningClasses: ["2° EM MB"], afternoonClasses: ["7° TC"] },
  { id: "room-44", number: "44", floor: "3º piso", segment: "Ensino Médio", morningClasses: ["1° EM MA"], afternoonClasses: ["9° TA"] },
  { id: "room-45", number: "45", floor: "3º piso", segment: "Ensino Médio", morningClasses: ["1° EM MB"], afternoonClasses: ["7° TA"] },
  { id: "room-46", number: "46", floor: "3º piso", segment: "Ensino Médio", morningClasses: ["3° EM MA"], afternoonClasses: ["8° TA"] },
];
